* lein-plz

  A Leiningen plugin for quickly adding dependencies to projects.

** Usage

   Suppose you want to add =clojurescript=, =core.async= and
   =data.json= to a project. Maybe you remember the latest versions
   off-hand (or at least, a valid one so that you can use lein
   ancient). You still have to type out the groupIds and -- anyway, it
   takes some typing.

   With =lein-plz=:

   #+BEGIN_SRC sh
     lein plz add async cljs json
   #+END_SRC

   and your =project.clj= is updated with the latest versions of each
   corresponding dependency. Users specify abbreviations to their
   desired brevity.

** Adding your own abbreviations

   =lein-plz= has fallback abbreviations, but it can be put to better
   use if you add some of your own. User specified maps get merged
   later.

   #+BEGIN_SRC clojure
   (merge fallback-abbreviation-map user-map-1 user-map-2 user-map-3 ...)
   #+END_SRC

   Each map should be in its own file:

   #+BEGIN_SRC clojure
   {:org.clojure/clojurescript   #{"clojurescript" "cljs"}
    :org.clojure/core.async      #{"core.async" "async"}
    :org.clojure/core.cache      #{"core.cache" "cache"}
    :org.clojure/core.logic      #{"core.logic" "logic"}
    :org.clojure/core.match      #{"core.match" "match"}
    :org.clojure/core.memoize    #{"core.memoize" "memoize"}
    :org.clojure/core.typed      #{"core.typed" "typed"}
    :org.clojure/data.json       #{"data.json" "json"}
    :org.clojure/data.xml        #{"data.xml" "xml"}
    :org.clojure/java.jdbc       #{"java.jdbc" "jdbc"}
    ;; Databases for jdbc
    :org.apache.derby/derby      #{"derby"}
    :hsqldb/hsqldb               #{"hsqldb"}
    :mysql/mysql-connector-java  #{"mysql"}
    :net.sourceforge.jtds/jtds   #{"jtds"}
    :postgresql/postgresql       #{"postgresql" "postgres"}
    :org.xerial/sqlite-jdbc      #{"sqlite"}

    :compojure                   #{"compojure"}
    :hiccup                      #{"hiccup"}
    :ring                        #{"ring"}}
   #+END_SRC

   The keywords are the full dependency, while each value is a set of
   abbreviations for that dependency.

   If that map resides in =/home/stuartsierra/.lein/plz/myplzmap.edn=,
   then =/home/stuartsierra/.lein/profiles.clj= should be:

   #+BEGIN_SRC clojure
     {:user {:plugins [[cider/cider-nrepl "0.8.0-SNAPSHOT"]
                       [lein-plz "0.1.0-SNAPSHOT"]
                       [slamhound "1.5.5"]]
             :plz ["/home/stuartsierra/.lein/plz/myplzmap.edn"]}}
   #+END_SRC

   There can be more maps:

   #+BEGIN_SRC clojure
     {:user {:plugins [[cider/cider-nrepl "0.8.0-SNAPSHOT"]
                       [lein-plz "0.1.0-SNAPSHOT"]
                       [slamhound "1.5.5"]]
             :plz ["/home/stuartsierra/.lein/plz/myplzmap.edn"
                   "/home/stuartsierra/.lein/plz/user-map-2.edn"
                   "/home/stuartsierra/.lein/plz/user-map-3.edn"]}}

     ;; (merge fallback-abbreviation-map user-map-1 user-map-2 user-map-3 ...)
     ;; so user-map-3 overwrites user-map-2 overwrites ...
   #+END_SRC
** Warnings
   Do not use relative paths.

   Also, this is quite new and untested. Only use this on
   project.clj's you can afford to throw away.

** Installation

   For now - as it has not yet been released - clone the repository,
   enter it and run =lein install=:

   #+BEGIN_SRC sh
     git clone https://github.com/johnwalker/lein-plz
     cd lein-plz & lein install
   #+END_SRC

   Finally, add =[lein-plz "0.1.0-SNAPSHOT"]= to the `:plugins` vector
   of your `:user` profile.


** License

   Copyright © 2014 John Walker

   Distributed under the Eclipse Public License either version 1.0 or
   any later version
